version: "3.9"
services:
  auth-postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airport
      - POSTGRES_PASSWORD=airport
      - POSTGRES_DB=airport
  auth-pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  auth-redis:
    image: redis
    ports:
      - "6379:6379"
