version: '3.9'

services:
  postgres1:
    image: postgres
    container_name: "my-postgres1"
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data1:/var/lib/postgresql/data
      - ./fake-data/TicketDatabase/:/fake-data/
      # - ./storage/postgres1/data:/var/lib/postgresql/data
    expose:
      - "5432"
    # ports:
    #   - target: 5432
    #     published: 5433
    #     protocol: tcp
    #     mode: host

  postgres2:
    image: postgres
    container_name: "my-postgres2"
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./fake-data/TicketDatabase/:/fake-data/
    expose:
      - "5432"
    # ports:
    #   - target: 5432
    #     published: 5434
    #     protocol: tcp
    #     mode: host

  redis:
    image: redis
    container_name: "my-redis"
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data
      # - ./storage/redis/data:/data
    expose:
      - "6379"
    # ports:
    #   - target: 6379
    #     published: 6380
    #     protocol: tcp
    #     mode: host
    environment:
      - REDIS_REPLICATION_MODE=master

  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: "my-dbeaver"
    restart: unless-stopped
    volumes:
      - dbeaver_workspace:/opt/cloudbeaver/workspace
    ports:
      - "8080:8978"
    depends_on:
      - redis
      - postgres1
      - postgres2


volumes:
    postgres_data1:
    postgres_data2:
    redis_data:
    dbeaver_workspace: